apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-toleration-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
      tolerations:
      - key: "environment"
        operator: "Equal"
        value: "dev"
        effect: "NoSchedule"
